version: '3.8'

services:
  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
      - ./backend/certs:/app/certs


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://archit:architagarwal@172.17.0.1:5432/eventease?schema=public
      - JWT_SECRET=ePf$A7h&1!jX@9zLd0^nUvR!w4*DqR2P
      - PORT=5000
    volumes:
      - ./backend:/app
      - ./backend/certs:/app/certs