version: '3.8'

services:
  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
      - ./backend/certs:/app/certs

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://archit:architagarwal@db:5432/eventease?schema=public
      - JWT_SECRET=ePf$A7h&1!jX@9zLd0^nUvR!w4*DqR2P
      - PORT=5000
    volumes:
      - ./backend:/app
      - ./backend/certs:/app/certs
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: eventease-db
    restart: always
    environment:
      POSTGRES_USER: archit
      POSTGRES_PASSWORD: architagarwal
      POSTGRES_DB: eventease
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
