global:
  scrape_interval: 15s  # Prometheus will scrape (pull metrics) every 15 seconds

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['eventease_backend:5000']  # Target 1

  - job_name: 'postgres'
    static_configs:
      - targets: ['eventease_postgres_exporter:9187']  # Target 2
