export const mockBookings = [
    {
      id: 1,
      eventName: "TechFest 2025",
      date: "2025-05-10",
      time: "5:00 PM",
      venue: "Main Auditorium",
      isCompleted: false, // Upcoming
      feedbackGiven: false,
    },
    {
      id: 2,
      eventName: "Cultural Night",
      date: "2025-04-20",
      time: "7:00 PM",
      venue: "Open Air Theater",
      isCompleted: true, // Past event
      feedbackGiven: false,
    },
    {
      id: 3,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 4,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 5,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 6,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 7,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 8,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
    {
      id: 9,
      eventName: "Art Expo",
      date: "2025-06-15",
      time: "3:00 PM",
      venue: "Exhibition Hall",
      isCompleted: false,
      feedbackGiven: false,
    },
  ];
  