export const mockEvents = [
  {
    id: 1,
    eventName: "TechFest 2025",
    date: "2025-05-10",
    time: "5:00 PM",
    venue: "Main Auditorium",
    isCompleted: false, // Upcoming event
    poster: "/images/defaultposter.png",
    description: "Join us for an exciting showcase of emerging technologies.",
    organizer: "Tech Club",
    registrationCount: 50,
    capacity: 100,
  },
  {
    id: 2,
    eventName: "Cultural Night",
    date: "2025-04-20",
    time: "7:00 PM",
    venue: "Open Air Theater",
    isCompleted: true, // Past event
    poster: "/images/defaultposter.png",
    description: "An evening of vibrant performances celebrating diverse cultures.",
    organizer: "Cultural Club",
    registrationCount: 80,
    capacity: 120,
  },
  {
    id: 3,
    eventName: "Art Expo",
    date: "2025-06-15",
    time: "3:00 PM",
    venue: "Exhibition Hall",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "Discover inspiring art pieces and meet local artists.",
    organizer: "Art Club",
    registrationCount: 30,
    capacity: 90,
  },
  {
    id: 4,
    eventName: "Music Mania",
    date: "2025-07-10",
    time: "6:30 PM",
    venue: "Concert Hall",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "An electrifying musical journey with live performances.",
    organizer: "Music Club",
    registrationCount: 75,
    capacity: 150,
  },
  {
    id: 5,
    eventName: "Literary Fest",
    date: "2025-08-05",
    time: "4:00 PM",
    venue: "Conference Room B",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "A celebration of words, with readings, discussions, and more.",
    organizer: "Literature Club",
    registrationCount: 40,
    capacity: 80,
  },
  {
    id: 6,
    eventName: "Science Symposium",
    date: "2025-09-12",
    time: "2:00 PM",
    venue: "Science Hall",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "Explore groundbreaking scientific research and experiments.",
    organizer: "Science Club",
    registrationCount: 60,
    capacity: 110,
  },
  {
    id: 7,
    eventName: "Drama Night",
    date: "2025-10-03",
    time: "7:30 PM",
    venue: "Theater Stage",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "A night of theatrical performances by talented students.",
    organizer: "Drama Club",
    registrationCount: 55,
    capacity: 100,
  },
  {
    id: 8,
    eventName: "Business Bootcamp",
    date: "2025-11-15",
    time: "9:00 AM",
    venue: "Conference Center",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "A hands-on workshop on entrepreneurship and business strategies.",
    organizer: "Business Club",
    registrationCount: 45,
    capacity: 80,
  },
  {
    id: 9,
    eventName: "Photography Workshop",
    date: "2025-12-01",
    time: "11:00 AM",
    venue: "Media Lab",
    isCompleted: false,
    poster: "/images/defaultposter.png",
    description: "Learn photography tips and tricks from seasoned professionals.",
    organizer: "Photography Club",
    registrationCount: 20,
    capacity: 50,
  },
];
